config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  # public pages routes
  get 'about' => 'pages#about_us'
  get 'contact' => 'pages#contact_us'
  get 'privacy-policy' => 'pages#privacy_policy'
  get 'terms-and-conditions' => 'pages#terms_and_conditions'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @title_text = 'Hello world!'
    @subtilte_text = 'I am learning Rails!'
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about_us
  end

  def contact_us
  end

  def privacy_policy
  end

  def terms_and_conditions
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/home/index.html.erb
<h1><%= @title_text %></h1>
<p><%= @subtitle_text %></p>
<%= render 'shared/links' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HrMitra</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">

    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about_us.html.erb
<h1>Pages#about_us</h1>
<p>Find me in app/views/pages/about_us.html.erb</p>
<%= render 'shared/links' %>

app/views/pages/contact_us.html.erb
<h1>Pages#contact_us</h1>
<p>Find me in app/views/pages/contact_us.html.erb</p>
<%= render 'shared/links' %>

app/views/pages/privacy_policy.html.erb
<h1>Pages#privacy_policy</h1>
<p>Find me in app/views/pages/privacy_policy.html.erb</p>
<%= render 'shared/links' %>

app/views/pages/terms_and_conditions.html.erb
<h1>Pages#terms_and_condions</h1>
<p>Find me in app/views/pages/terms_and_condions.html.erb</p>
<%= render 'shared/links' %>

app/views/shared/_links.html.erb
<%= link_to 'About Us', about_path, target: '_blank', style: 'color:green' %>
<%= link_to 'Contact Us', contact_path, target: '_blank', style: 'color:green'%>
<%= link_to 'Privacy Policy', privacy_policy_path, target: '_blank', style: 'color:green' %>
<%= link_to 'Terms and Conditions', terms_and_conditions_path, target: '_blank', style: 'color:green' %>